sequenceDiagram
  participant GA as go-amadeus-trip<br>API
  participant BG as go-amadeus-trip<br>background process
  participant M as GMail
  participant A as Amadeus
  participant D as SQLite
  loop every x seconds
    BG ->> M: retrieve emails
    BG ->> A: post new parsing job
    BG ->> A: refresh job status
    BG ->> A: get job results
    BG ->> D: write results
  end
  BG ->> GA: expose trip information